import math 
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
# Basic Arithematic Operations
# print(f"{num1} + {num2} = {num1 + num2}")
# print(f"{num1} - {num2} = {num1 - num2}")
# print(f"{num1} * {num2} = {num1 * num2}")
# print(f"{num1} / {num2} = {num1 / num2}")
# print(f"{num1} % {num2} = {num1 % num2}")
# print(f"{num1} // {num2} = {num1 // num2}")
# print(f"{num1} ** 9 = {num1 ** 9}")
# print(f"{num2} ** 7 = {num2 ** 7}")
# Advance Mathematical Operations
# print(f"math.sin({num2}) = {math.sin(num2)}")
# print(f"math.cos({num1}) = {math.cos(num1)}")
# print(f"math.tan({num2}) = {math.tan(num2)}")
# print(f"math.sinh({num1}) = {math.sinh(num1)}")
# print(f"math.cosh({num2}) = {math.cosh(num2)}")
# print(f"math.tanh({num1}) = {math.tanh(num1)}")
# print(f"math.exp({num2}) = {math.exp(num2)}")
# print(f"math.fabs({num1}) = {math.fabs(num1)}")
# print(f"math.degrees({num2}) = {math.degrees(num2)}")
# print(f"math.radians({num1}) = {math.radians(num1)}")
# print(f"math.ceil(1091.87) = {math.ceil(1091.87)}")
# print(f"math.floor(1212.12) = {math.floor(1212.12)}")
# print(f"math.factorial({num2}) = {math.factorial(num2)}")
# print(f"math.sqrt({num1}) = {math.sqrt(num1)}")
# print(f"math.isqrt({num2}) = {math.isqrt(num2)}")
# print(f"math.lcm({num1}, {num2}) = {math.lcm(num1, num2)}")
# print(f"math.gcd({num1}, {num2}) = {math.gcd(num1, num2)}")
# print(f"math.isnan({num1}) = {math.isnan(num1)}")
# print(f"math.isclose({num1}, {num2}) = {math.isclose(num1, num2)}")
# print(f"math.isfinite(10201919192912912) = {math.isfinite(10201919192912912)}")
# print(f"math.log({num2}) = {math.log(num2)}")
# print(f"math.log10({num1}) = {math.log10(num1)}")